### ISSUE TITLE
Setup Lume website for Sapial.ai

### ISSUE THREAD

**Issue by chrissotraidis** [sapial-ai/sapial#5]
Use Deno Lume to create a basic website as a github repo. 
Just host on github pages to start.

**Subtasks:**

- [x] Sapial website structure
- [x] Shell of website (styles/libraries) ready for devs
- [ ] Finish and polish copy
- [ ] Export code and put it into Deno
